apiVersion: apps/v1
kind: Deployment
metadata:
  name: payslip-app
  labels:
    app: payslip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payslip
  template:
    metadata:
      labels:
        app: payslip
    spec:
      containers:
      - name: payslip-container
        image: latest # Ensure this matches your image name in the Pushed step
        ports:
        - containerPort: 8086 # Change this to the port your app uses
